### ISSUE TITLE
Go through required endpoints and add eventual endpoints to program

### ISSUE THREAD

**Issue by RebeckaOcampoSandgren** [RebeckaOcampoSandgren/HumansVsZombies-Backend#22]
Read through the case (API requirements) to find eventual reporting methods that needs to be added to the program. If found then add methods to the controllers.

**Comment by FadiAkkaoui** [comment]
Game - GET - Return list of chat messages, POST - send new chat.
Squad - GET - Return a list of squad messages, POST - Send a new chat message addressed to a particular squad, GET - Get a list of squad check-in markers, POST - Create a squad checkin.

**Comment by RebeckaOcampoSandgren** [comment]
Also adding reporting methods to get all human global chats and to get all zombie global chats
